### ISSUE TITLE
There may be  an error when calculating the number of peaks matched

### ISSUE THREAD

**Issue by TututuXi** [compomics/spectrum_similarity#1]
![image](https://user-images.githubusercontent.com/15766876/37273593-406d94a2-2615-11e8-91b2-ec6dd17747f9.png)
Because the existence of **fragment tolerance**, a peak may match two or more peaks. Like the picture show, p3 will match p1 and p2. However, in your code(`/src/main/java/cal/cumulativeBinomialProbability/spectra/CompareAndScore.java` line from 150 to 215), you did not use a array to store all possible matching peaks but only use a variable to store one possible matching peak. Is it a problem？
Thanks

**Comment by Genet-Abay** [comment]
Hello,
Thank you for your question. For peak match finding only one peak is selected to be best match according to the algorithm. Peaks are already pre-filtered and peaks with highest intensity above threshold selected in advance. And then the peak which is closest to the query peak is selected best match. In that function we are trying to find whether the given peak has a match or not in given fragment tolerance, not the number of match peak found.

**Comment by TututuXi** [comment]
Hello, 
Thank you for your answer! But I still have some question. 
- 1. you mentioned **best match**， Whether is it necessary to record all matching peaks of the query peak and then the closest one is selected. (their mz value are closest)
- 2. I have read your paper **A pipeline for differential proteomics in unsequenced species**. When calculating intensity-based score， the equation is used.
![image](https://user-images.githubusercontent.com/15766876/37326126-ac483f9a-26cb-11e8-86f7-72dd6d03eb5f.png)
I can not understand the meaning of the equation. However I learned from your code
![image](https://user-images.githubusercontent.com/15766876/37327212-55fc0b9e-26d0-11e8-9eda-fac79d46bbd0.png)
is it right?
Thanks!
